# Generated by Django 5.2.8 on 2026-03-30 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_user_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_artist_ids", models.JSONField(blank=True, default=list)),
                ("top_genres", models.JSONField(blank=True, default=list)),
                ("top_track_ids", models.JSONField(blank=True, default=list)),
                ("avg_tempo", models.FloatField(blank=True, null=True)),
                ("avg_energy", models.FloatField(blank=True, null=True)),
                ("avg_zcr", models.FloatField(blank=True, null=True)),
                ("avg_rms", models.FloatField(blank=True, null=True)),
                ("avg_centroid", models.FloatField(blank=True, null=True)),
                ("avg_mfcc", models.JSONField(blank=True, default=list)),
                ("genre_diversity_score", models.FloatField(blank=True, null=True)),
                ("artist_diversity_score", models.FloatField(blank=True, null=True)),
                ("cluster_id", models.IntegerField(blank=True, null=True)),
                ("persona_type", models.CharField(blank=True, max_length=100)),
                ("persona_tags", models.JSONField(blank=True, default=list)),
                ("feature_vector", models.JSONField(blank=True, default=list)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("shared_genres", models.JSONField(blank=True, default=list)),
                ("shared_artists", models.JSONField(blank=True, default=list)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["similarity_score"],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
