# Generated by Django 5.2.8 on 2026-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_spotifytoken_userprofile_usermatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="top_artist_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="top_artist_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
