# Generated by Django 5.2.8 on 2026-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_userprofile_top_artist_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avg_spectral_contrast",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avg_spectral_flatness",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
