# Generated by Django 4.2.8 on 2026-04-17 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_userprofile_avg_spectral_contrast_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avg_mfcc",
        ),
    ]
