# Generated by Django 5.2.8 on 2026-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_userprofile_avg_mfcc"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="ticketmaster_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
